# Generated by Django 4.2.4 on 2023-08-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_picture', models.ImageField(upload_to='projects/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=20)),
                ('projects', models.ManyToManyField(to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=40)),
                ('projects', models.ManyToManyField(to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(max_length=40)),
                ('paragraph_text', models.CharField(max_length=200)),
                ('paragraph_image', models.ImageField(upload_to='projects/details/pictures')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_id', models.IntegerField()),
                ('paragraph_image', models.ImageField(upload_to='projects/details/equations')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.paragraph')),
            ],
        ),
    ]
