# Generated by Django 4.2.4 on 2023-08-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_tools_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='projects',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='equation',
            old_name='paragraph_image',
            new_name='queation_image',
        ),
    ]
