# Generated by Django 4.2.4 on 2023-08-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_equation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_picture',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
