# Generated by Django 4.2.4 on 2023-08-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_technique_projects_remove_tool_projects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
